apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: marginal-lizard-java-quarkus
  janus-idp.io/tekton: marginal-lizard-java-quarkus
  backstage.io/kubernetes-id: marginal-lizard-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: marginal-lizard-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
